baseURL: http://example.org/
languageCode: en-us
title: "Trevor Wolfe Portfolio"
theme: "toha"

params:
  # copyright
  copyright: © 2020 Copyright.

  # background image of the landing page
  background: "images/background.png"

  # GitHub repo URL of your site
  gitRepo: https://github.com/hossainemruz/toha-example-site

  # specify whether you want to write blog post or not
  enableBlogPost: false

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.

  # some information about you
  author:
    name: "Trevor Wolfe"
    image: "images/avatar.png"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "trevor@bigemailenergy.com"
    # a summary of what you do
    summary: 
      - I am a developer
      - I work with node and python
      - I love to work on fun projects